language: de
developer_mode: false
wait_time_file_closed: 3
reset_countdown_seconds: 3
close_on_no_person_enabled: true
close_on_no_person_seconds: 10
no_person_check_interval_ms: 2000
animation_speed: 15
fullscreen: true
photo_delay: 3
face_yolo:
  confidence: 0.5
pool:
  enabled: true
  path: ./pool
  max_extra_persons: 3
  cooldown_batches: 3
pipeline:
- id: moondream
  name: Visual Description (VLM)
  enabled: true
  watch_dir: ./General ordner/final
  file_ext: .yaml
  show_preview: true
  prompt: Name the clothing and any accessories the person is wearing. Put in 4 Sentences
- id: deepface
  name: Emotionserkennung
  enabled: true
  watch_dir: ./General ordner/final
  file_ext: .yaml
  use_retinaface: true
- id: fer
  name: Emotionserkennung (FER)
  enabled: false
  watch_dir: ./General ordner/final
  file_ext: .yaml
llm_model: llama3.2:1b
pipeline_timeout_seconds: 120
