services:
  deepface-app:
    build: .
    container_name: deepface_project_container
    volumes:
      - .:/app
      - ./deepface_weights:/root/.deepface/weights
      - ../main_image:/app/main_image
      - ./deepface_inbox:/app/deepface_inbox
      - ../faces_yolo:/app/faces_yolo
      - ../final:/app/final
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
