version: '3.8'

services:
  face-extraction:
    build: .
    container_name: body_extraction_app
    # Verhindert, dass der Container sofort nach Fehlern beendet wird (optional)
    restart: unless-stopped
    volumes:
      # Verknüpft das aktuelle Verzeichnis (.) mit /app im Container
      - .:/app
      
      # Greift auf den globalen Ordner "main_image" eine Ebene höher zu
      - ../main_image:/app/main_image
      
      # Falls die Ergebnisse in den globalen "faces_yolo" Ordner sollen:
      - ../body_yolo:/app/body_yolo
      
      # Cache-Ordner: Verhindert erneutes Herunterladen der KI-Modelle
      - ./models_cache/rembg:/root/.u2net
      - ./models_cache/yolo:/app/models
    environment:
      # Sorgt dafür, dass Python-Logs sofort im Terminal erscheinen
      - PYTHONUNBUFFERED=1