version: '3.8'

services:
  face-processor:
    build: .
    container_name: face_extraction_app
    volumes:
      # Verknüpft das aktuelle Verzeichnis (.) mit /app im Container
      - .:/app
      - ../../config.yaml:/app/config.yaml
      
      # Greift auf den globalen Ordner "main_image" eine Ebene höher zu
      - ../main_image:/app/main_image

      - ../final:/app/final

      - ../sketch:/app/sketch

      - ../docker-compose-deepface/deepface_inbox:/app/deepface_inbox

      - ../moondream_ai/moondream_inbox:/app/moondream_inbox
      - ../debug_body:/app/debug_body
      
      # Falls die Ergebnisse in den globalen "faces_yolo" Ordner sollen:
      - ../faces_yolo:/app/faces_yolo
      
      # Cache für Modelle (angepasst an deine Struktur)
      - ./models_cache:/root/.u2net 
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]