version: '3.8'

services:
  face-processor:
    build: .
    container_name: face_extraction_app
    volumes:
      # Verknüpft deine lokalen Ordner mit dem Container
      - .:/app
      - ./main_image:/app/main_image
      - ./faces_yolo:/app/faces_yolo
      # Optional: Cache für KI-Modelle, damit sie nicht jedes Mal laden
      - ./models_cache:/root/.u2net 
    environment:
      - PYTHONUNBUFFERED=1s